Repository GIGA-JET/MHLB-BE, pull requests merged in 2023-03, with the labels that each got.

#2 기본 세팅
  src/main/java/com/gigajet/mhlb/common/dto/SendMessageDto.java
  src/main/java/com/gigajet/mhlb/common/entity/Timestamped.java
  src/main/java/com/gigajet/mhlb/common/util/SuccessCode.java
  src/main/java/com/gigajet/mhlb/config/MyStompConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/UserRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/user/repository/UserRepository.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/exception/CustomException.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
  src/main/java/com/gigajet/mhlb/exception/GlobalExceptionHandler.java
  src/main/java/com/gigajet/mhlb/security/filter/CustomAccessDeniedHandler.java
  src/main/java/com/gigajet/mhlb/security/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/gigajet/mhlb/security/jwt/JwtAuthFilter.java
  src/main/java/com/gigajet/mhlb/security/jwt/JwtUtil.java
  src/main/java/com/gigajet/mhlb/security/user/UserDetailsImpl.java
  src/main/java/com/gigajet/mhlb/security/user/UserDetailsServiceImpl.java
Labels: Feature

#4 Refactor,Fix: 코드 수정, 이메일 체크 수정
  src/main/java/com/gigajet/mhlb/common/dto/SendMessageDto.java
  src/main/java/com/gigajet/mhlb/common/util/SuccessCode.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/UserRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/security/user/UserDetailsImpl.java
Labels: Fix, Refactor

#7 Dev
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/ChangeMypageDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
Labels: Feature

#8 Dev
  src/main/java/com/gigajet/mhlb/domain/managing/controller/ManagingController.java
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/entity/Workspace.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceUser.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceUserRepository.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Feature

#9 Feat: 비밀번호 찾기 이메일 인증 메일 발송, 캐시 저장
  src/main/java/com/gigajet/mhlb/config/RedisConfig.java
  src/main/java/com/gigajet/mhlb/domain/mail/controller/MailController.java
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
Labels: Feature

#10 Refector: mypage 반환값 수정
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Feature

#12 Dev
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
Labels: Refactor

#13 Feat: 이미지 업로드 구현
  src/main/java/com/gigajet/mhlb/common/util/S3Handler.java
  src/main/java/com/gigajet/mhlb/config/S3Config.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/managing/controller/ManagingController.java
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/ChangeMypageDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/controller/WorkspaceUserController.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/service/WorkspaceUserService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Fix, Refactor, Feature

#14 Refactor: image API 명세서에 맞춰 매개변수 이름 변경
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Refactor

#15 Dev
  src/main/java/com/gigajet/mhlb/common/util/SuccessCode.java
  src/main/java/com/gigajet/mhlb/domain/status/controller/StatusController.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/RedisStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/SqlStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/RedisStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/SqlStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/StatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/status/sse/StatusSseHandler.java
Labels: Feature

#17 Feat: Google 소셜 로그인 구현
  src/main/java/com/gigajet/mhlb/common/util/SuccessCode.java
  src/main/java/com/gigajet/mhlb/config/RestTemplateConfig.java
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/managing/controller/ManagingController.java
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/dto/ManagingResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/status/sse/StatusSseHandler.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/GoogleOAuthRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/user/service/OAuthService.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/domain/user/social/GoogleOAuth.java
  src/main/java/com/gigajet/mhlb/domain/user/social/SocialOAuth.java
  src/main/java/com/gigajet/mhlb/domain/user/social/SocialType.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/service/WorkspaceUserService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Fix, Refactor, Feature

#19 Refactor: 워크스페이스 순서변경기능 추가 및 초대 예외처리 추가
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceOrder.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceUser.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceInviteRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceOrderRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceUserRepository.java
Labels: Fix, Refactor, Feature

#21 Dev
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceInviteRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceUserRepository.java
Labels: Refactor, Feature

#22 Feat, Refactor: user 다시 조회 -> Query, Mypage 코드 리팩터
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/user/repository/UserRepository.java
Labels: Refactor, Feature

#23 Refactor: Status 기능 보강 및 코드 일부 수정
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/status/controller/StatusController.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/SqlStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/SqlStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/status/sse/StatusSseHandler.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/entity/Workspace.java
  src/main/java/com/gigajet/mhlb/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceOrder.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceUser.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceInviteRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceOrderRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceUserRepository.java
Labels: Fix, Refactor

#24 Feat: 비밀번호 찾기 난수 유효 검사 추가
  src/main/java/com/gigajet/mhlb/common/util/SuccessCode.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/mail/controller/MailController.java
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/UserRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Fix, Refactor, Feature

#25 Feat: 시간확인 aop 작성 및 status refactor
  src/main/java/com/gigajet/mhlb/common/util/TimeCheckAop.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/RedisStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/SqlStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/StatusEnum.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/SqlStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Refactor, Feature

#26 Refactor: Status refactor
  src/main/java/com/gigajet/mhlb/domain/status/entity/SqlStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/StatusEnum.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/SqlStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
Labels: Refactor

#27 Feat: nav 이미지 조회
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Feature, Style

#28 Refactor: 워크스페이스 순서변경기능 추가
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceOrderRepository.java
Labels: Fix, Refactor

#29 Feat: 비회원 워크스페이스 초대
  src/main/java/com/gigajet/mhlb/domain/mail/controller/MailController.java
  src/main/java/com/gigajet/mhlb/domain/mail/dto/MailResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Feature

#30 Refactor: StatusEnum 요구사항에 맞게 수정
  src/main/java/com/gigajet/mhlb/domain/status/entity/StatusEnum.java
Labels: Refactor

#32 Feat: 몽고db시작
  src/main/java/com/gigajet/mhlb/config/StompConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/chat/controller/ChatController.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatResponse.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/Chat.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/ChatRoom.java
  src/main/java/com/gigajet/mhlb/domain/chat/repository/ChatRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/status/sse/StatusSseHandler.java
Labels: Feature

#33 Feat: Stomp를 이용한 웹 소켓 연결 구현
  src/main/java/com/gigajet/mhlb/common/util/TimeCheckAop.java
  src/main/java/com/gigajet/mhlb/config/StompConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/chat/controller/ChatController.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/Chat.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/ChatRoom.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/UserAndMessage.java
  src/main/java/com/gigajet/mhlb/domain/chat/repository/ChatRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/SqlStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/status/sse/StatusSseHandler.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Refactor, Feature

#34 Feat: 비밀번호 암호화 업그레이드
  src/main/java/com/gigajet/mhlb/common/util/AESUtil.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/security/jwt/JwtUtil.java
Labels: Feature

#35 Refactor: 요청사항에 따른 정렬기능 변경
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
Labels: Refactor

#38 Feat: 이미지 리사이징, 디폴트 이미지 추가
  src/main/java/com/gigajet/mhlb/common/util/S3Handler.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Feature
