Repository GIGA-JET/MHLB-BE, pull requests merged in 2023-04, with the labels that each got.

#39 Refactor: 웹소켓 토큰 및 읽지않은 메시지 구현
  src/main/java/com/gigajet/mhlb/config/StompConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSocketInterceptor.java
  src/main/java/com/gigajet/mhlb/domain/chat/controller/ChatController.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/Chat.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/ChatRoom.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/UserAndMessage.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/SqlStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/security/jwt/JwtUtil.java
Labels: Refactor, Feature

#41 Refactor: 워크스페이스 리스트에 adnim일 시 맨 앞으로 정렬되게 수정, 거절 기능 구현
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Refactor

#42 Refactor: 워크스페이스 리스트에 adnim일 시 맨 앞으로 정렬되게 수정, 거절 기능 구현
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageResponseDto.java
Labels: Refactor

#43 Refactor: 워크스페이스 리스트에 adnim일 시 맨 앞으로 정렬되게 수정, 거절 기능 구현
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/repository/WorkspaceUserRepository.java
Labels: Refactor

#45 Fix: userRole, 나간유저 재초대 기능 수정
  src/main/java/com/gigajet/mhlb/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceOrder.java
  src/main/java/com/gigajet/mhlb/domain/workspaceuser/entity/WorkspaceUser.java
Labels: Fix, Refactor

#46 Refactor: 마이페이지 워크스페이스 리스트에서 admin순, 같을 시 이름순으로 변경
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Refactor

#47 Refactor: 마이페이지 워크스페이스 초대 수락, 거절 api 하나로 합치기
  src/main/java/com/gigajet/mhlb/common/util/SuccessCode.java
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Refactor

#48 Refactor: 기획의도에 맞게 코드 수정
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
Labels: Refactor

#50 Refactor: 마이페이지 워크스페이스 초대 수락, 거절 api 하나로 합치기, boolean으로 처리하던 부분 해결
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/dto/MypageRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
Labels: Refactor

#53 Feat, Fix: mulipart file 확장자 제한, multipart file 최대 크기 초과 예외 핸들링 GJ-302 GJ-303
  src/main/java/com/gigajet/mhlb/common/dto/SendMessageDto.java
  src/main/java/com/gigajet/mhlb/common/util/ImageUtil.java
  src/main/java/com/gigajet/mhlb/common/util/S3Handler.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
  src/main/java/com/gigajet/mhlb/exception/GlobalExceptionHandler.java
Labels: Fix, Feature

#55 Feat: user info validation
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/UserRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/exception/GlobalExceptionHandler.java
Labels: Fix, Refactor, Feature

#56 Feat: Swagger config GJ-331
  src/main/java/com/gigajet/mhlb/common/dto/SendMessageDto.java
  src/main/java/com/gigajet/mhlb/config/OpenApiConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
Labels: Feature

#59 Refactor: 웹소켓 리팩토링
  src/main/java/com/gigajet/mhlb/MhlbApplication.java
  src/main/java/com/gigajet/mhlb/common/util/TimeCheckAop.java
  src/main/java/com/gigajet/mhlb/config/AlarmSubscriber.java
  src/main/java/com/gigajet/mhlb/config/ChatSubscriber.java
  src/main/java/com/gigajet/mhlb/config/RedisConfig.java
  src/main/java/com/gigajet/mhlb/config/StatusSubscriber.java
  src/main/java/com/gigajet/mhlb/config/StompConfig.java
  src/main/java/com/gigajet/mhlb/config/WebSecurityConfig.java
  src/main/java/com/gigajet/mhlb/domain/chat/controller/ChatController.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/entity/MessageId.java
  src/main/java/com/gigajet/mhlb/domain/chat/repository/ChatRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/repository/MessageIdRepository.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/status/controller/StatusController.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Refactor, Feature

#60 Hotfix: api 명세서에 따른 수정
  src/main/java/com/gigajet/mhlb/domain/chat/controller/ChatController.java
Labels: Fix

#61 Fix: google oauth redirect 프론트로 옮김 GJ-304
  src/main/java/com/gigajet/mhlb/domain/mail/service/MailService.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/GoogleOAuthRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/user/service/OAuthService.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/domain/user/social/GoogleOAuth.java
  src/main/java/com/gigajet/mhlb/exception/ErrorCode.java
Labels: Fix, Refactor

#63 Feat: 알림기능 추가, 유저 이미지 부분 id값 추가해서 user로 도메인 이동
  src/main/java/com/gigajet/mhlb/config/AlarmSubscriber.java
  src/main/java/com/gigajet/mhlb/domain/alarm/Entity/Alarm.java
  src/main/java/com/gigajet/mhlb/domain/alarm/Entity/AlarmTypeEnum.java
  src/main/java/com/gigajet/mhlb/domain/alarm/Repository/AlarmRepository.java
  src/main/java/com/gigajet/mhlb/domain/alarm/dto/AlarmRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/controller/MypageController.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/UserResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
Labels: Feature

#64 Refactor: 알림기능 추가, 유저 이미지 코드 수정
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
Labels: Refactor

#66 Refactor: isShow 타입 Boolean으로 변경
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/managing/service/ManagingService.java
  src/main/java/com/gigajet/mhlb/domain/mypage/service/MypageService.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/user/controller/UserController.java
  src/main/java/com/gigajet/mhlb/domain/user/dto/UserResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/user/entity/User.java
  src/main/java/com/gigajet/mhlb/domain/user/service/UserService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/entity/Workspace.java
  src/main/java/com/gigajet/mhlb/domain/workspace/entity/WorkspaceOrder.java
  src/main/java/com/gigajet/mhlb/domain/workspace/entity/WorkspaceUser.java
  src/main/java/com/gigajet/mhlb/domain/workspace/repository/WorkspaceOrderRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspace/repository/WorkspaceUserRepository.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
Labels: Refactor

#67 Refactor: SqlStatus -> Status로 이름 변경, MessageId에서 발생하는 동시성 문제 해결
  src/main/java/com/gigajet/mhlb/domain/chat/controller/ChatController.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/RedisStatus.java
  src/main/java/com/gigajet/mhlb/domain/status/entity/Status.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/RedisStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/SqlStatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/repository/StatusRepository.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/workspace/service/WorkspaceService.java
Labels: Refactor

#68 Refactor: 알람 기능 수정
  src/main/java/com/gigajet/mhlb/common/service/AlarmSubscriber.java
  src/main/java/com/gigajet/mhlb/domain/alarm/Repository/AlarmRepository.java
  src/main/java/com/gigajet/mhlb/domain/alarm/dto/AlarmRequestDto.java
  src/main/java/com/gigajet/mhlb/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
Labels: Refactor

#70 Refactor: 웹소켓 수정
  src/main/java/com/gigajet/mhlb/config/AlarmSubscriber.java
  src/main/java/com/gigajet/mhlb/config/RedisConfig.java
  src/main/java/com/gigajet/mhlb/config/StatusSubscriber.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/domain/status/dto/StatusResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/status/service/StatusService.java
  src/main/java/com/gigajet/mhlb/domain/workspace/repository/WorkspaceUserRepository.java
Labels: Refactor

#73 Refactor: 불필요한 코드 제거
  src/main/java/com/gigajet/mhlb/config/StompConfig.java
Labels: Refactor

#74 Feat: 메세지 읽었을 때 다 읽지 않아도 응답, 채팅방 uuid response에 추가
  src/main/java/com/gigajet/mhlb/domain/alarm/dto/ChatAlarmResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatMessageService.java
  src/main/java/com/gigajet/mhlb/domain/chat/service/ChatService.java
  src/main/java/com/gigajet/mhlb/global/listener/StompEventListener.java
  src/main/java/com/gigajet/mhlb/global/subscriber/ChatAlarmSubscriber.java
  src/main/java/com/gigajet/mhlb/global/subscriber/StatusSubscriber.java
  src/main/java/com/gigajet/mhlb/global/subscriber/WorkspaceInviteAlarmSubscriber.java
Labels: Feature
